window.runViewerChecks = async function () {
  const {DiagramViewer} = await import('../dist/viewer.js');
  const checks = [];
  const check = (name, ok, details = {}) => {
    checks.push({name, ok, details});
    if (!ok) throw new Error(`${name}: ${JSON.stringify(details)}`);
  };
  const tick = () => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)));
  const content = document.createElement('content');
  content.style.cssText = 'position:fixed;inset:0;overflow:auto;width:auto;background:white';
  const write = document.createElement('div');
  write.id = 'write';
  write.innerHTML = '<p style="font-size:17px">Document remains readable.</p><div class="md-diagram"><div class="md-diagram-panel-preview"></div></div>';
  const svg = document.querySelector('#diagrams svg').cloneNode(true);
  svg.classList.add('mermaid-svg');
  write.querySelector('.md-diagram-panel-preview').append(svg);
  content.append(write);
  document.body.append(content);
  const original = write.innerHTML;
  const font = getComputedStyle(write.querySelector('p')).fontSize;
  const viewer = new DiagramViewer();
  await tick();
  try {
    let nativeClicks = 0;
    const nativeClick = () => nativeClicks++;
    write.addEventListener('click', nativeClick);
    svg.querySelector('text').dispatchEvent(new MouseEvent('click', {bubbles: true}));
    await tick();
    check('direct click opens preview without native editor click', !viewer.panel.hidden && nativeClicks === 0);
    write.removeEventListener('click', nativeClick);
    check('open centered preview without moving document', !viewer.panel.hidden && !viewer.backdrop.hidden && content.style.right === '0px' && viewer.panel.getAttribute('aria-modal') === 'true');
    const start = viewer.zoom;
    viewer.root.querySelector('[data-action="in"]').click();
    check('zoom changes diagram only', viewer.zoom > start && getComputedStyle(write.querySelector('p')).fontSize === font && write.innerHTML === original);
    const y = viewer.y;
    viewer.canvas.dispatchEvent(new WheelEvent('wheel', {deltaY: 50, cancelable: true}));
    check('trackpad wheel pans diagram', viewer.y === y - 50);
    const zoom = viewer.zoom;
    viewer.canvas.dispatchEvent(new WheelEvent('wheel', {ctrlKey: true, deltaY: -20, clientX: 400, clientY: 200, cancelable: true}));
    check('modified wheel zooms diagram', viewer.zoom > zoom);
    viewer.root.querySelector('[data-action="actual"]').click();
    check('actual size is 100 percent', viewer.zoom === 1);
    viewer.root.querySelector('[data-action="fit"]').click();
    check('fit contains whole graph', viewer.svgWidth * viewer.zoom <= viewer.canvas.clientWidth && viewer.svgHeight * viewer.zoom <= viewer.canvas.clientHeight);
    check('document width remains unchanged', Math.abs(content.getBoundingClientRect().width - innerWidth) < 1);
    check('view interactions do not alter export source', write.innerHTML === original);
    viewer.canvas.dispatchEvent(new KeyboardEvent('keydown', {key: 'Escape', bubbles: true, composed: true}));
    await tick();
    check('Escape closes without changing document width', viewer.panel.hidden && content.style.right === '0px' && content.style.width === 'auto');
    let focused = false;
    let refreshed = false;
    const codeMirror = document.createElement('div');
    codeMirror.className = 'CodeMirror';
    codeMirror.CodeMirror = {focus() { focused = true; }, refresh() { refreshed = true; }};
    svg.closest('.md-diagram').prepend(codeMirror);
    viewer.root.querySelector('.launch').click();
    check('explicit edit focuses native source editor', focused && refreshed && viewer.panel.hidden);
    codeMirror.remove();
    viewer.show(svg);
    viewer.backdrop.click();
    check('clicking outside closes preview', viewer.panel.hidden);
    viewer.show(svg);
    const replacement = svg.cloneNode(true);
    replacement.querySelector('text').textContent = 'Updated label';
    svg.replaceWith(replacement);
    await tick();
    check('document rerender refreshes viewer', viewer.stage.textContent.includes('Updated label'));
    viewer.destroy();
    check('unload removes controls and restores layout', !document.getElementById('codex-mermaid-viewer') && content.style.right === '0px');
  } finally {
    viewer.destroy();
    content.remove();
  }
  return checks;
};
